### ISSUE TITLE
where is 'go' language support?

### ISSUE THREAD

**Issue by sugs2014** [tmr88/first#2]
wonna it NOW

**Comment by tmr88** [comment]
Are you **dumb**?
Are you `**dumb**`?
Are you \*\*dumb**?

* list item
* list item

- [x] Finish my changes
- [ ] Push my commits to GitHub
- [ ] Open a pull request

calling for @sugs2014 

calling issue #2

**Comment by tmr88** [comment]
:1234: :8ball: :100: :santa:

**Comment by tmr88** [comment]
calling for @sugs2014
